### ISSUE TITLE
删除一个节点后，所有展开的节点都折叠了。

### ISSUE THREAD

**Issue by qriv** [huanglong6828/vue-tree-grid#16]
删除按钮 删除一个节点后，所有展开的节点都折叠了。能不能保持当前展开都节点状态？

**Comment by huanglong6828** [comment]
@qriv 因为删除节点后 需要重新初始化数据  你可以参考下面提问默认展开节点 添加代码

**Comment by qriv** [comment]
@huanglong6828 在操作展开树都时候，怎么把每个节点都expanded值都保存下来？

**Comment by huanglong6828** [comment]
@qriv  你可以在每次初始化的时候添加属性 告诉组件展开

**Comment by qriv** [comment]
@huanglong6828 可能我没描述清楚吧。 1.我把 树节点都展开。2，点删除按钮删除其中一个节点，现在是整个树都折叠了，我想要保持我刚才操作都树节点还是展开的状态。

**Comment by huanglong6828** [comment]
@qriv  哦哦哦 明白了 这样解决 你删除了节点 不用重新给组件新数据，这样组件就不会重新渲染。 下次进入在重新渲染数据

**Comment by qriv** [comment]
@huanglong6828 怎么才能把删除的行动态删掉。

**Comment by qriv** [comment]
@huanglong6828 点击删除时，我后台请求删除数据。 前端也需要动态删掉那一行把。

**Comment by qriv** [comment]
👌
